---
title: "UseR_PosterAbstract2016"
author: "Myfanwy Johnston"
date: "March 24, 2016"
output: html_document
---


## Encounters of the Chinook kind: visualizing fish movement with R

Biotelemetry (the electronic tagging and tracking of organisms) is notorious for producing large data sets.  Finding ways to visualize these data sets is an ongoing effort in ecology; ideally we want to convey not only summary statistics (movement rates, turning angles, etc), but also insight into animal behavior itself.  The movements and migrations of anadromous fish, which are often constrained within the linear boundaries of a river system or delta and only monitored intermittently with acoustics, present a special challenge to effective visualization.  Excellent individual examples of visualization of fish migration can be found piecemeal in the literature and 'in the wild' (read: on the internet), but no central repository or reference volume currently exists on the topic.  Thus, fisheries ecologists and behaviorists often find themselves having to reinvent the wheel when it comes to data visualization of their acoustic datasets, or worse, never visualize them at all.  In hopes of providing a common starting point for these researchers and all other interested parties, this poster collects and presents examples of visualization of fish movement and migration using tools in R, including applications with ggplot2, googleVis, leaflet, and Shiny, among others.  Code and reproducible examples of all visualization workflows and datasets are available in the github repository: http://github.com/Myfanwy/SeeFishMove.
